apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "postal.fullname" . }}
data:
  postalConfig: |
  {{- if .Values.postal.config }}
{{ toYaml .Values.postal.config | indent 4 }}
  {{- else }}
    userConfig: false
  {{- end }}
