apiVersion: v1
kind: Service
metadata:
  name: {{ template "postal.fullname" . }}-web
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "postal.name" . }}
    component: postal
  ports:
  - name: web
    port: 5000
    targetPort: web
