{{- if .Values.postal.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "postal.fullname" . }}-web
  labels:
    app: {{ template "postal.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.postal.web.ingress.ingressClass }}
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  {{- if .Values.postal.web.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ required "postal.web.ingress.hostname is required " .Values.postal.web.ingress.hostname }}
    {{- if .Values.postal.web.existingTlsSecret }}
    secretName: {{ .Values.postal.web.existingTlsSecret }}
    {{- else }}
    secretName: {{ template "postal.fullname" . }}-web-tls
    {{- end }}
  {{- end }}
  rules:
  - host: {{ required "postal.web.ingress.hostname is required " .Values.postal.web.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "postal.fullname" . }}-web
            port: 
              number: 5000
{{- end }}
